services:  
  - name: google
    request:
    request-url: https://www.google.com
    period: 5
    failures-count: 2
    requests-count: 4
    timeout: 1.5
    post: false
    slacks:
      - https://hooks.slack.com/services/blablabla